name: CI

on: [push, pull_request]

jobs:
  build:
    name: Lint and Install Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Check black formatting
        run: black --check T-Conf

      - name: Run flake8 linting
        run: flake8 T-Conf

      - name: Check CLI loads
        run: tconf --help
